[tool.black]
line-length = 128
target-version = ['py39', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
asyncio_mode = "auto"
log_format = "%(asctime)s.%(msecs)03d %(levelname)s %(message)s"
